export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS'
export const ADD_TO_FAVORITES_FAILURE = 'ADD_TO_FAVORITES_FAILURE'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS'
export const REMOVE_FROM_FAVORITES_FAILURE = 'REMOVE_FROM_FAVORITES_FAILURE'
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES'
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS'
export const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE'
export const FETCH_SPECIFIC_MOVIE = 'FETCH_SPECIFIC_MOVIE'
export const FETCH_SPECIFIC_MOVIE_SUCCESS = 'FETCH_SPECIFIC_MOVIE_SUCCESS'
export const FETCH_SPECIFIC_MOVIE_FAILURE = 'FETCH_SPECIFIC_MOVIE_FAILURE'
export const RESET_SPECIFIC_MOVIE = 'RESET_SPECIFIC_MOVIE'
export const SEARCH_TERM = 'SEARCH_TERM'
export const SEARCH_TERM_SUCCESS = 'SEARCH_TERM_SUCCESS'
export const SEARCH_TERM_FAILURE = 'SEARCH_TERM_FAILURE'
export const RESET_TORRENTS = 'RESET_TORRENTS'
export const SEARCH_TORRENTS = 'SEARCH_TORRENTS'
export const SEARCH_TORRENTS_SUCCESS = 'SEARCH_TORRENTS_SUCCESS'
export const SEARCH_TORRENTS_FAILURE = 'SEARCH_TORRENTS_FAILURE'
export const ADD_TORRENT = 'ADD_TORRENT'
export const ADD_TORRENT_SUCCESS = 'ADD_TORRENT_SUCCESS'
export const ADD_TORRENT_FAILURE = 'ADD_TORRENT_FAILURE'
export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_CATEGORIES = 'GET_MOVIES_CATEGORIES'
export const GET_MOVIES_CATEGORIES_SUCCESS = 'GET_MOVIES_CATEGORIES_SUCCESS'
export const GET_MOVIES_CATEGORIES_FAILURE = 'GET_MOVIES_CATEGORIES_FAILURE'
export const GET_RECOMMENDED_MOVIES = 'GET_RECOMMENDED_MOVIES'
export const GET_RECOMMENDED_MOVIES_SUCCESS = 'GET_RECOMMENDED_MOVIES_SUCCESS'
export const GET_RECOMMENDED_MOVIES_FAILURE = 'GET_RECOMMENDED_MOVIES_FAILURE'
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES'
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS'
export const GET_TOP_RATED_MOVIES_FAILURE = 'GET_TOP_RATED_MOVIES_FAILURE'

export default {
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  ADD_TO_FAVORITES,
  ADD_TO_FAVORITES_SUCCESS,
  ADD_TO_FAVORITES_FAILURE,
  REMOVE_FROM_FAVORITES,
  REMOVE_FROM_FAVORITES_SUCCESS,
  REMOVE_FROM_FAVORITES_FAILURE,
  FETCH_POPULAR_MOVIES,
  FETCH_POPULAR_MOVIES_SUCCESS,
  FETCH_POPULAR_MOVIES_FAILURE,
  FETCH_SPECIFIC_MOVIE,
  FETCH_SPECIFIC_MOVIE_SUCCESS,
  FETCH_SPECIFIC_MOVIE_FAILURE,
  SEARCH_TERM,
  SEARCH_TERM_SUCCESS,
  SEARCH_TERM_FAILURE,
  RESET_TORRENTS,
  SEARCH_TORRENTS,
  SEARCH_TORRENTS_SUCCESS,
  SEARCH_TORRENTS_FAILURE,
  ADD_TORRENT,
  ADD_TORRENT_SUCCESS,
  ADD_TORRENT_FAILURE,
  GET_MOVIES,
  GET_MOVIES_CATEGORIES,
  GET_RECOMMENDED_MOVIES,
  GET_TOP_RATED_MOVIES
}
